#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"

while [ -h $SOURCE ]; do
	TARGET=$(readlink "$SOURCE")
	if [[ $SOURCE == /* ]]; then
		SOURCE="$TARGET"
	else
		DIR=$(dirname $SOURCE)
		SOURCE="$DIR/$TARGET"
	fi
done

DIR=$(cd -P $(dirname $SOURCE) && pwd)

JARFILE="$DIR/build/libs/pacchat.jar"

java -jar $JARFILE $@

